/*
 * Where an AI agent finds out about this site.
 *
 * Six addresses that all say the same thing in different formats, and one rule how a page
 * becomes Markdown. They are listed here and only here, because five places have to agree on
 * them: the link elements in app/app.vue, the Link header in server/plugins/agenten.ts, the
 * handlers under server/routes/.well-known/, the texts in server/utils/agenten-texte.ts and the
 * test in test/agenten.spec.ts. A path that only exists as a string literal in the handler would
 * be missing from the header the day after.
 *
 * The names of the paths are not freely chosen: /.well-known/api-catalog is the endpoint from
 * RFC 9727, /.well-known/ai-catalog.json the one from the ARD specification, and
 * /.well-known/agent.md and the Agent Skills index are the addresses the tools in this field probe
 * for. Which is the point — discovery only works at the address that is looked up. /auth.md is the
 * odd one out and sits at the site root rather than under /.well-known/, because that is where the
 * Auth.md convention puts it.
 */

/** The endpoints agents are pointed to, with the link relation each is announced under. */
export const agentPaths = {
  /** Machine-readable agent documentation: tasks, boundaries, contact points. */
  agentDoc: '/.well-known/agent.md',
  /** The catalogue of machine-readable endpoints, as an RFC 9727 linkset. */
  apiCatalog: '/.well-known/api-catalog',
  /** The same endpoints as an ARD capability manifest, for registries that index agent sites. */
  aiCatalog: '/.well-known/ai-catalog.json',
  /** Index of the published Agent Skills. */
  skillIndex: '/.well-known/agent-skills/index.json',
  /**
   * What an agent has to do to get access here — namely nothing, per the Auth.md convention.
   *
   * At the site root, not under /.well-known/: the convention names /auth.md, and the scanners
   * that check for it ask for exactly that address.
   */
  authDoc: '/auth.md',
  /** The site guidance for language models, generated by nuxt-llms. */
  llms: '/llms.txt',
  sitemap: '/sitemap.xml',
} as const

/*
 * The one skill this site publishes: reading its published content.
 *
 * Deliberately not a second skill for appointment requests. server/api/kontakt.post.ts serves the
 * form of this site, is rate limited per IP address and sends an email that a person answers by
 * hand — an endpoint an agent should call, that is not. Agents pass the request on to the form or
 * to the email address, and that is what the agent documentation says.
 */
export const agentSkill = {
  /** Stable identifier. Appears in the index, in skill.md and in its URL. */
  name: 'shapeandflow-inhalte',
  description:
    'Lesender Zugriff auf die veröffentlichten Inhalte von Shape & Flow als aktuelles Markdown.',
} as const

/** Address of the skill description belonging to {@link agentSkill}. */
export const skillPath = `/.well-known/agent-skills/${agentSkill.name}/skill.md`

/**
 * The address at which a page is also available as Markdown.
 *
 * `/preise` becomes `/preise.md`, and the home page becomes `/.md` — the convention the tools in
 * this field expect, and the one the `Accept: text/markdown` header answers with at the canonical
 * URL as well.
 */
export function markdownPath(route: string): string {
  const path = route.replace(/\/+$/, '')
  return path === '' ? '/.md' : `${path}.md`
}

/** One discovery link, as a link element in the head and as a Link header at the same time. */
export interface DiscoveryLink {
  /** The link relation. `alternate`, `describedby` and `service-doc` are registered; the two
   * others are the names the tools in this field look for. */
  rel: string
  type: string
  /** Absolute path, without the host: the head takes it as is, the header prefixes the site. */
  href: string
}

/**
 * What every page announces about itself and about this site.
 *
 * One list for the link elements in app/app.vue and the Link header in
 * server/plugins/agenten.ts. HTTP header and markup have to say the same, otherwise an agent
 * that only reads headers gets a different answer than one that parses the HTML — and the head is
 * missing for a request that never asks for HTML at all.
 */
export function discoveryLinks(route: string): DiscoveryLink[] {
  return [
    { rel: 'alternate', type: 'text/markdown', href: markdownPath(route) },
    { rel: 'service-doc', type: 'text/markdown', href: agentPaths.agentDoc },
    { rel: 'api-catalog', type: 'application/linkset+json', href: agentPaths.apiCatalog },
    { rel: 'ai-catalog', type: 'application/json', href: agentPaths.aiCatalog },
    { rel: 'agent-skills', type: 'application/json', href: agentPaths.skillIndex },
    { rel: 'describedby', type: 'text/plain', href: agentPaths.llms },
  ]
}
